### ISSUE TITLE
Version 0.1.0 doesn't work because of missing dependency

### ISSUE THREAD

**Issue by Kurren123** [zmx0142857/vscode-markdown-asciimath#2]
OS version: Windows 11 version 22H2
VSCode version: 1.81.1 

I install the plugin via VScode and paste the following into a markdown file with the following result:

![image](https://github.com/zmx0142857/vscode-markdown-asciimath/assets/3525980/33a869ce-b5f8-4296-9e42-478c0291ecd5)

I have even installed the asciimath parser via npm separately, no luck. Any help would be much appreciated.

**Comment by zmx0142857** [comment]
It seems to be a problem with dependencies, and I'm working on it. For now, you may want to install the old version of this plugin.
And thanks for providing this issue.

**Comment by zmx0142857** [comment]
Fixed by version 0.1.1

**Comment by Kurren123** [comment]
Amazing, thank you
